APPL_COBJS += balancer.o balancer_param.o

APPL_CXXOBJS += BalancerCpp.o \
                Battery.o \
				ColorSensor.o \
				GyroSensor.o \
				Motor.o \
				PID.o \
				RunGarage.o \
				RunGate.o \
				RunMain.o \
				RunNormal.o \
				RunSeesaw.o \
				TouchSensor.o \
				SonarSensor.o \

SRCLANG := c++
